language: python

services:
  - postgresql

python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"

env:
  - DJANGO="django==1.7.4"
  - DJANGO="django==1.6.10"
  - DJANGO="django==1.5.12"

matrix:
  exclude:
    - python: "2.6"
      env: DJANGO="django==1.7.4"

branches:
  only:
    - master
    - drf-3.0

# command to install requirements
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install ordereddict; fi
  - pip install $DJANGO
  - pip install -r requirements-test.txt
  - python setup.py -q install

before_script:
  - createdb django_restframework_gis
  - psql -U postgres -d django_restframework_gis -c "CREATE EXTENSION postgis;"
  - psql -U postgres -d django_restframework_gis -c "CREATE EXTENSION postgis_topology;"

# command to run tests, e.g. python setup.py test
script:
  - coverage run --source=rest_framework_gis,django_restframework_gis_tests runtests.py

after_success:
  coveralls