dist: trusty
sudo: false
language: python
cache: pip
addons:
  postgresql: "9.3"
  apt:
    packages:
      - postgresql-9.3-postgis-2.3
services:
  - postgresql

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36-django111
    - python: 3.6
      env: TOXENV=py36-django110
    - python: 3.6
      env: TOXENV=py36-django19
    - python: 3.6
      env: TOXENV=py36-django18

    - python: 3.5
      env: TOXENV=py35-django110

    - python: 3.4
      env: TOXENV=py34-django110

    - python: 2.7
      env: TOXENV=py27-django111
    - python: 2.7
      env: TOXENV=py27-django110
    - python: 2.7
      env: TOXENV=py27-django19
    - python: 2.7
      env: TOXENV=py27-django18

branches:
  only:
    - master

install:
  - pip install coverage tox

before_script:
  - createdb django_restframework_gis
  - psql -U postgres -d django_restframework_gis -c "CREATE EXTENSION postgis;"

script:
  - coverage run --source=rest_framework_gis $(command -v tox)

after_success:
  coveralls
