language: python

services:
  - postgresql

python:
  - "2.7"
  - "2.6"

env:
  - DJANGO="django==1.5.8"
  - DJANGO="django==1.6.5"

branches:
  only:
    - master 

# command to install requirements
install:
  - pip install $DJANGO
  - pip install psycopg2 djangorestframework coverage coveralls django-filter --use-mirrors
  - python setup.py -q install

before_script:
  - createdb django_restframework_gis
  - psql -U postgres -d django_restframework_gis -c "CREATE EXTENSION postgis;"
  - psql -U postgres -d django_restframework_gis -c "CREATE EXTENSION postgis_topology;"

# command to run tests, e.g. python setup.py test
script:
  - coverage run --source=rest_framework_gis,django_restframework_gis_tests setup.py test

after_success:
  coveralls