sudo: false
language: python
cache: pip

services:
  - postgresql

python:
  - "3.5"
  - "3.4"
  - "2.7"
  

env:
  - DJANGO="django==1.8.7"
  - DJANGO="django==1.7.11"
  - DJANGO="django==1.9"
  

matrix:
  exclude:
    - python: "3.5"
      env: DJANGO="django==1.7.11"
    
    

branches:
  only:
    - master

# command to install requirements
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install ordereddict; fi
  - pip install $DJANGO
  - pip install -r requirements-test.txt
  - python setup.py -q develop

before_script:
  - createdb django_restframework_gis
  - psql -U postgres -d django_restframework_gis -c "CREATE EXTENSION postgis;"

# command to run tests, e.g. python setup.py test
script:
  - coverage run --source=rest_framework_gis runtests.py

after_success:
  coveralls
